### PR TITLE
First deployment of application.

### PR DESCRIPTION
**Pull request by mkajic20**
**This pull request is the first deployment of the web application.**

**It contains the following features:**

All users:
- User registration
- User login
- User logout
- Map of all chargers that shows their current availability

Customer users:
- RFID card management 
- Charging history 

Admin users:
- User management 
- RFID card management of all cards
- Management of all chargers 
- Monthly statistics of chargers 
- Charging history of all users' charges

### CODE REVIEW

**Review by lraknic — APPROVED** [review]
Tested and everything looks good.

**Review by irosic20 — APPROVED** [review]
Everything works fine. Good job!

**Review by tsisko20 — APPROVED** [review]
Everything works good.

**Review by lgaljer20 — APPROVED** [review]
Tested all features and tried to find bugs but was unsuccessful.

**Pull request merged**
